services:
  app:
    platform: linux/arm64

    build:
      context: .

      dockerfile: Dockerfile

    volumes:
      - ./:/var/www

    depends_on:
      - db

  web:
    platform: linux/arm64
    image: nginx:alpine
    ports:
      - "8180:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    platform: linux/arm64

    image: mariadb:11

    environment:
      MYSQL_DATABASE: propedeutico

      MYSQL_USER: propedeutico

      MYSQL_PASSWORD: secret

      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306" # no choca con 3306

    volumes:
      - dbdata:/var/lib/mysql

  pma:
    platform: linux/arm64
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080" # Adminer expone 8080
    depends_on:
      - db

  composer:
    platform: linux/arm64

    image: composer:2

    working_dir: /var/www

    volumes:
      - ./:/var/www

volumes:
  dbdata:

networks:
  default:
    name: propedeutico-net
